from django.urls import path
from . import views

app_name = "news_app"

urlpatterns = [
     path("", views.home, name="home"),
     path("register/", views.register_view, name="register"),
     path("login/", views.login_view, name="login"),
     path("logout/", views.logout_view, name="logout"),
     path("dashboard/", views.dashboard, name="dashboard"),
     path("articles/", views.article_list, name="article_list"),
     path("articles/<int:article_id>/",
          views.article_detail, name="article_detail"),
     path("publishers/", views.publisher_list, name="publisher_list"),
     path("journalists/", views.journalist_list, name="journalist_list"),
     path("publishers/<int:publisher_id>/subscribe/",
          views.publisher_subscribe, name="publisher_subscribe"),
     path("publishers/<int:publisher_id>/unsubscribe/",
          views.publisher_unsubscribe, name="publisher_unsubscribe"),
     path("publishers/create/",
          views.publisher_create, name="publisher_create"),
     path("journalists/<int:journalist_id>/subscribe/",
          views.journalist_subscribe, name="journalist_subscribe"),
     path("journalists/<int:journalist_id>/unsubscribe/",
          views.journalist_unsubscribe, name="journalist_unsubscribe"),
     path("my-articles/", views.my_articles, name="my_articles"),
     path("my-articles/create/", views.article_create, name="article_create"),
     path("my-articles/<int:article_id>/edit/",
          views.article_edit, name="article_edit"),
     path("my-articles/<int:article_id>/delete/",
          views.article_delete, name="article_delete"),
     path("editor/pending/",
          views.editor_pending_articles, name="editor_pending_articles"),
     path("editor/articles/<int:article_id>/approve/",
          views.editor_approve_article, name="editor_approve_article"),
     path("newsletters/", views.newsletter_list, name="newsletter_list"),
     path("newsletters/<int:newsletter_id>/", views.newsletter_detail,
          name="newsletter_detail"),
     path("my-newsletters/", views.my_newsletters, name="my_newsletters"),
     path("my-newsletters/create/", views.newsletter_create, name="newsletter_create"),
     path("my-newsletters/<int:newsletter_id>/edit/", views.newsletter_edit,
          name="newsletter_edit"),
     path("my-newsletters/<int:newsletter_id>/delete/", views.newsletter_delete,
          name="newsletter_delete"),
     path("editor/newsletters/pending/", views.editor_pending_newsletters,
          name="editor_pending_newsletters"),
     path("editor/newsletters/<int:newsletter_id>/approve/",
          views.editor_approve_newsletter,
          name="editor_approve_newsletter"),
     path("editor/articles/", views.editor_articles, name="editor_articles"),
     path("editor/articles/<int:article_id>/edit/", views.editor_article_edit,
          name="editor_article_edit"),
     path("editor/articles/<int:article_id>/delete/", views.editor_article_delete,
          name="editor_article_delete"),
     path("editor/newsletters/", views.editor_newsletters, name="editor_newsletters"),
     path("editor/newsletters/<int:newsletter_id>/edit/", views.editor_newsletter_edit,
          name="editor_newsletter_edit"),
     path("editor/newsletters/<int:newsletter_id>/delete/",
          views.editor_newsletter_delete, name="editor_newsletter_delete"),
]
